### ISSUE TITLE
Notebooks aren't shown when connecting from another browser

### ISSUE THREAD

**Issue by leruaa** [polynote/polynote#1340]
**Description**
I have set up a Polynote instance on my server with Docker, and when I connect to it on a different browser, the notebooks I created on the first one are not shown.

**Environment**
```
docker run --rm -it \
  -p 8192:8192 \
  -v $(pwd)/config.yml:/opt/config/config.yml \
  -v $(pwd)/notebooks:/opt/notebooks/ \
  polynote/polynote:0.4.6-2.12 \
  --config /opt/config/config.yml
```
config.yml:
```
listen:
  host: 0.0.0.0

storage:
  dir: /opt/notebooks
  mounts:
    examples:
      dir: examples
```

Otherwise, please provide the following information:
- Polynote Version: 0.4.6
- Operating System: Linux
