### ISSUE TITLE
Running polynote behind an nginx proxy 

### ISSUE THREAD

**Issue by alexlipa91** [polynote/polynote#579]
I've deployed polynote on a remote machine and now I want the UI to be accessible through browser. It all works fine using ssh port-forwarding. I was try to setup some rules with nginx (which I already use to proxy things like jupyter). This is the basic rule I used

    `location /polynote {
           proxy_pass              http://localhost:8192;
           proxy_pass_request_headers on;
     }`

When trying to connect from the browser to `hostname-machine:/polynote' I see connections arriving in the server log but the browser page remains blank and no errors is logged anywhere

   `[blaze-selector-1] INFO org.http4s.blaze.channel.nio1.NIO1SocketServerGroup - Accepted connection from /127.0.0.1:46673`

Do you have any idea on how to debug this? 
Maybe some incompatibility between nginx and blaze?
Are there any other logs I can check or is there a way to enable debugging logger?

**Comment by jonathanindig** [comment]
Hi @alexlipa91, thanks for checking out Polynote! Do you see any errors in the browser console when you try to load the browser page? I assume you are using Chrome and have tried a hard refresh (cmd+shift+r on Mac). 

Polynote is known to work behind an nginx proxy, but unfortunately I'm not an nginx expert so I can't be much help debugging your configuration.

**Comment by alexlipa91** [comment]
unfortunately no errors in the console. I just see this in the network tab which seems indicating the response arrived correctly 
`HTTP/1.1 200 OK
Server: nginx
Date: Tue, 29 Oct 2019 22:48:51 GMT
Content-Length: 0
Connection: keep-alive
Last-Modified: Thu, 24 Oct 2019 00:19:38 GMT` 
but still blank page

**Comment by alexlipa91** [comment]
comparing with a working local instance of polynote, it looks like static files (css) and javascript are not being requested (or loaded)

**Comment by alexlipa91** [comment]
apparently polynote assumes that all static files are served from the root of the webserver. A guy in my company helped me out on this, not really my main expertise. We are patching the code here https://github.com/polynote/polynote/blob/master/polynote-frontend/index.html#L7 and adding a publicPath to the webpack

**Comment by b4ux1t3** [comment]
There's another consideration here:

Polynote uses websockets to implement some of its functionality. As such, you can't just do a vanilla reverse proxy. In fact, I wasn't even able to get it working with just passing through the headers, per the config in your initial post.

Fortunately, setting the headers within Nginx itself to upgrade the connection works just fine.

So, assuming you're using a default installation of Nginx on Ubuntu (a safe bet, I think, and these steps should be generalizable to any Nginx deployment), your best bet is to explicitly define the `/ws` location to proxy directly to the app's URL:

    location /ws {
        proxy_pass http://localhost:8192/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

You will have to define a map in the root `http` directive, likely in your `/etc/nginx/nginx.conf`:

    http {

	    map $http_upgrade $connection_upgrade {
        	default upgrade;
        	''      close;
	    }
    . . .
    }

Presto! That should sort you out!

Now, some might question using a discrete location directive, since you could just add these lines in the default `/` location. The thing is, I'm trying to account for if, for whatever reason, Polynote one day starts accepting web sockets on a different port than the normal application traffic.

Hope that helps!

**Comment by alexlipa91** [comment]
thanks for the reply and the fix! We figured out the websocket problem, however we are still struggling to have the javascript code pointing the right path.
We fixed it modifying the webpack json and rebuilding polynote. I was wondering if it might be parametric too.

**Comment by alexlipa91** [comment]
hi! Rebuilding polynote with the modified webpack json seems to work however every time I refresh the page we get the app to point again to the root of the webserver (which in our nginx setup points to another server on another port). My questions are 
- do you reckon the limitation of the current setup (i.e. the webpack.json pointing to the root) or this is a problem of my own setup?
- do you have any idea on how to fix the reload problem mentioned above?

**Comment by jeremyrsmith** [comment]
@alexlipa91 It looks like a bunch of JS still uses absolute paths, which is probably the source of this issue. Hopefully #650 will fix it.

**Comment by jonathanindig** [comment]
Closing for now assuming that #650 solved the problem. Please feel free to reopen if you're still running into trouble with this!

**Comment by dm3ll3n** [comment]
I am able to reproduce this with NGINX and the latest PolyNote Docker image. Additionally, I get this exact same behavior when trying to put ShinyProxy in front of PolyNote. It's a shame, as PolyNote running behind ShinyProxy would allow for multiple secured instances, and it seems so close.

Here are the files used in the attempted setup…

* docker-compose.yml

```
version: '3.5'

services:
  shinyproxy:
    image: openanalytics/shinyproxy
    networks:
      - polynote
    ports:
      - 8080:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './application.yml:/opt/shinyproxy/application.yml'

networks:
  polynote:
    name: polynote
```

* application.yml (shinyproxy config file)

```
proxy:
  title: PolyNote testing
  hide-navbar: false
  admin-groups: ['admins']
  authentication: simple
  users:
  - name: admin
    password: admin
    groups: admins
  port: 8080
  landing-page: /
  container-wait-time: 30000
  heartbeat-rate: 15000
  heartbeat-timeout: 120000
  docker:
    internal-networking: true
  specs:
    - id: polynote
      display-name: PolyNote
      description: Full Screen
      container-image: polynote/polynote
      container-network: polynote
      container-volumes:
        - '/absolute/path/to/config.yml:/opt/polynote/config.yml'
      port: 8192
      access-groups: [ 'admins' ]
```

* config.yml (polynote config file)

```
listen:
  host: 0.0.0.0
  port: 8192

ui:
  base_uri: /
```
