### ISSUE TITLE
Failed to initialize SparkContext when running with yarn-cluster mode inside Docker

### ISSUE THREAD

**Issue by withsmilo** [polynote/polynote#581]
I tested if `Polynote v0.2.8` connects to our in-house Spark cluster normally using yarn-cluster mode inside Docker, but got failed. Here is my config.yml for testing.
```yml
listen:
  host: 0.0.0.0
  port: 8192

spark:
  spark.master: yarn
  spark.submit.deployMode: cluster
  spark.jars.packages: <OUR_PACKAGES>
  spark.jars.repositories: <OUR_REPOS>
  spark.app.name: polynote_test
  spark.driver.userClasspathFirst: true
  spark.executor.userClasspathFirst: true
```
When `Polynote v0.2.8` executes the following `spark-submit` command to deploy a remote kernel client to our Spark cluster, there was a problem of waiting indefinitely to initialize SparkContext.
```
[INFO]  Deploying with command:
        spark-submit 
--class polynote.kernel.remote.RemoteKernelClient 
--driver-java-options "-Dlog4j.configuration=log4j.properties -Djava.library.path=/usr/bin/python3.6/site-packages/jep:/usr/local/nvidia/lib:/usr/local/nvidia/lib64" 
--deploy-mode cluster 
--jars file:/polynote/deps/polynote-spark-runtime.jar,file:/polynote/deps/polynote-runtime.jar 
--conf spark.executor.userClasspathFirst=true 
--conf spark.app.name=polynote_test 
--conf spark.jars.repositories=<OUR_REPOS> 
--conf spark.jars.packages=<OUR_PACKAGES> 
--conf spark.driver.userClasspathFirst=true 
--conf spark.master=yarn /polynote/polynote.jar --address 172.17.0.2 --port 39830 --kernelFactory polynote.kernel.LocalSparkKernelFactory
```
I think that the Spark Driver cannot connect `Polynote` because `172.17.0.2` is the internal IP address of running container.

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the issue report!

I guess you would have to set the `spark.driver.host` and `spark.driver.port` configurations, to point to your host instead of the container. And you'd have to configure docker to bind the port that Spark uses for communicating.

Not sure if this is in scope for polynote itself, though. What do you think?

**Comment by withsmilo** [comment]
@jeremyrsmith 
Thanks for quick reply! I tested that both `spark.driver.host` and `spark.driver.port` configurations are not valid with YARN-cluster mode. So I think that `Polynote` is not compatible with the **YARN-cluster mode** inside Docker yet.

Next, I tested it with **YARN-client mode** inside Docker, and had success to do it. Here is my config.yml.
```yaml
listen:
  host: 0.0.0.0
  port: 8192

spark:
  spark.master: yarn
  spark.jars.packages: <OUR_PACKAGES>
  spark.jars.repositories: <OUR_REPOS>
  spark.app.name: polynote_test
  spark.driver.userClasspathFirst: true
  spark.executor.userClasspathFirst: true
  spark.driver.host: <HOST_IP>
  spark.driver.port: 8193
  spark.driver.bindAddress: 0.0.0.0
  spark.blockManager.port: 8194
  spark.ui.enabled: false
```
And here is my docker command.
```bash
$ docker run -it -p 8192:8192 -p 8193:8193 -p 8194:8194 <DOCKER_IMAGE> /bin/bash
```
