### ISSUE TITLE
Suggestion: docker-compose for simpler usage

### ISSUE THREAD

**Issue by tlazaro** [polynote/polynote#666]
Hi!

I think the docker [doc](https://github.com/polynote/polynote/tree/master/docker) has several steps which could be reduced to running `docker-compose up` provided the command is run with these files in the local directory:

`config.yml`:
```yml
listen:
  host: 0.0.0.0

storage:
  dir: /opt/notebooks
  mounts:
    examples:
      dir: examples
```

`docker-compose.yml`:
```yml
version: "3.4"
services:
  polynote:
    image: polynote/polynote:latest
    environment:
      - PYSPARK_ALLOW_INSECURE_GATEWAY=1
    volumes: 
      - .:/opt/config
      - ./notebooks:/opt/notebooks
    ports:
      - "8192:8192"
      - "4040-4050:4040-4050"
    entrypoint: ['./polynote/polynote.py', "--config", "/opt/config/config.yml"]
```
(thanks to @duhruh who suggested and wrote the docker compose file).

To start: `docker-compose up`
To stop: `docker-compose stop`

These two files could be included in a directory in the repo, without having the user create them manually in a separate directory.

As a comparison the instructions in the [doc](https://github.com/polynote/polynote/tree/master/docker) require creating the first file and then running this command:

```bash
docker run --rm -it -p 127.0.0.1:8192:8192 -p 127.0.0.1:4040-4050:4040-4050 -v `pwd`:/opt/config -v `pwd`/notebooks:/opt/notebooks polynote/polynote:latest --config /opt/config/config.yml
```

What do you think?
