### ISSUE TITLE
Support repository credentials

### ISSUE THREAD

**Issue by JD557** [polynote/polynote#698]
It would be nice to support credentials for private ivy2/maven repositories.

**Comment by JD557** [comment]
I was playing a bit with this idea by changing the `IvyRepository`/`MavenRepository` definitions, but that ends up storing the credentials in the notebook which, in retrospect, sounds like a bad idea.

I was thinking about adding a more general `credentials` key to the config, which could store other credentials as well. Something like:

```
credentials:
  - ivy:
      base: https://my-artifacts.org/
      username: user1
      password: password0
  - ivy:
      base: https://my-custom-ivy-repo.org/
      username: user1
      password: password0
  - s3:
      base: http://central.maven.org/maven2/
      access_key: DUMMYAWSACCESSKEY
      secret_key: DUMMYAWSSECRETKEY
```

WDYT?
