### ISSUE TITLE
matplotlib broken for pyspark kernels in 0.2.14

### ISSUE THREAD

**Issue by kervel** [polynote/polynote#706]
**Description**
I am unable to use matplotlib in pyspark kernels in polynote 0.2.14 (worked in previous release). It also still works in non-pyspark python kernels.

The problem is that the "kernel" global variable is no longer set in pyspark kernels. This "kernel" variable is needed by the polynote matplotlib backend.

**Reproduction**
1. create a pyspark notebook
2. do:
```python
import matplotlib.pyplot as plt
plt.scatter([1,2,3],[4,5,6])
plt.show()
```
3. observe the NameError "kernel" is not defined.

**Environment**
```Dockerfile
FROM ubuntu:19.10

ARG spark_jars=jars
ARG img_path=kubernetes/dockerfiles
ARG k8s_tests=kubernetes/tests

ENV DEBIAN_FRONTEND noninteractive

RUN set -ex && \
    apt-get update && \
    apt-get -y install openjdk-8-jdk bash tini python3-pip python3-dev build-essential python3-setuptools && \
    mkdir -p /opt/spark && \
    mkdir -p /opt/spark/work-dir && \
    touch /opt/spark/RELEASE && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    echo "auth required pam_wheel.so use_uid" >> /etc/pam.d/su && \
    chgrp root /etc/passwd && chmod ug+rw /etc/passwd


COPY ${spark_jars} /opt/spark/jars
COPY bin /opt/spark/bin
COPY sbin /opt/spark/sbin
COPY ${img_path}/spark/entrypoint.sh /opt/
COPY examples /opt/spark/examples
COPY ${k8s_tests} /opt/spark/tests
COPY data /opt/spark/data
### workaround spark incompat with newer kubernetes versions
RUN rm /opt/spark/jars/kubernetes-client-4*
COPY kubernetes-client-4.4.2.jar /opt/spark/jars/
ENV SPARK_HOME /opt/spark
RUN mkdir ${SPARK_HOME}/python

COPY python/lib ${SPARK_HOME}/python/lib
ENV PYTHONPATH ${SPARK_HOME}/python/lib/pyspark.zip:${SPARK_HOME}/python/lib/py4j-*.zip
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

RUN pip3 install jep jedi virtualenv seaborn xlrd xlsxwriter pandas matplotlib py4j koalas
RUN ln -sf /usr/bin/tini /sbin/tini

WORKDIR /opt/
ARG POLYNOTE_VERSION=0.2.14
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install curl wget && pip3 install matplotlib
RUN curl -L https://github.com/polynote/polynote/releases/download/${POLYNOTE_VERSION}/polynote-dist.tar.gz \
  | tar -xzvpf -
ADD config.yml /opt/polynote/config.yml
EXPOSE 8192
ENV PATH="${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"
ENV PYTHONPATH="${SPARK_HOME}/python/:${PYTHONPATH}"
ENV PYSPARK_ALLOW_INSECURE_GATEWAY=1

CMD bash polynote/polynote
```

**Configuration**
```yaml
    listen:
      host: 0.0.0.0

    storage:
      dir: /opt/notebooks
      mounts:
        examples:
          dir: examples

    dependencies:
      scala:
          - org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.4
          - org.apache.hadoop:hadoop-aws:2.7.0
          - file:///opt/extra/trellis_rasterize-assembly-0.1.jar
    spark:
      spark.master: k8s://https://kubernetes.default.svc:443
      spark.submit.deployMode: client
      spark.executor.instances: 3
      spark.serializer: org.apache.spark.serializer.KryoSerializer
      spark.kryo.registrator: geotrellis.spark.store.kryo.KryoRegistrator
      spark.kubernetes.container.image: registry.gitlab.com/kapernikov/intern/ts_bigdata_cloud/spark/spark-py
      spark.kubernetes.namespace: poly
      spark.driver.host: spark-driver.poly.svc
      spark.kubernetes.container.image.pullSecrets: gitlab
      spark.executor.memory: 6g
      spark.kryoserializer.buffer.max: 1024m

```
