### ISSUE TITLE
Ivy credentials / Artifactory

### ISSUE THREAD

**Issue by leobenkel** [polynote/polynote#786]
I searched for `artifactory` https://github.com/polynote/polynote/issues?utf8=%E2%9C%93&q=artifactory but didn't find answers.

I am adding a new resolver in the `repositories` key in the `config.yml` :

```
repositories:
  - ivy:
      base: https://artifactory._______.com/artifactory
      artifact_pattern: com._______
```

and later in the file: 

```
credentials:
  - coursier:
      path: ~/path/to/credentials
  - ivy:
      path: ~/path/to/credentials
```

But i still get an error when I launch the notebook with: 

```
Error downloading [______]
unauthorized: https://artifactory._____.com/artifactory/_____ (Artifactory Realm)
```
