### ISSUE TITLE
broken host configuration in 0.3.5 (latest) release

### ISSUE THREAD

**Issue by antonkulaga** [polynote/polynote#851]
After I updated my docker-compose with latest polynote it stoped working!
I had the following configuration
```
listen:
  host: 0.0.0.0
  port: 8192

repositories:
  - maven:
      base: http://central.maven.org/maven2/
  - maven:
      base: http://oss.sonatype.org/content/repositories/snapshots
      changing: true
  - maven:
      base: https://dl.bintray.com/comp-bio-aging/main/
      changing: true
```
however it looks like polynote stoped understanding the host config
