### ISSUE TITLE
Antlr class conflict when running SQL code in a notebook using Delta Lake

### ISSUE THREAD

**Issue by ludovicc** [polynote/polynote#946]
**Description**

Antlr class conflict when running SQL code in a notebook using Delta Lake.

**Reproduction**
1. ...
2. ...

**Environment**

Using a variant of https://github.com/mbari-org/docker-polynote/blob/master/Dockerfile.jdk11

- Polynote Version: 0.3.11
- Operating System: Ubuntu:19.10
- The command you are using to start Polynote: polynote/polynote.py

- Any other details that might be useful, such as whether you are running Polynote as a service, using a custom script, etc.  

Polynote in a custom Docker image with Spark 3.0, Delta Lake 0.7

**Configuration**

```
dependencies:
  scala:
    - io.delta:delta-core_2.12:0.7.0

spark:
  properties:
    spark.driver.memory: 4g
    spark.executor.memory: 8g
    spark.driver.userClasspathFirst: true
    spark.executor.userClasspathFirst: true
  spark_submit_args: "--packages io.delta:delta-core_2.12:0.7.0 --conf \"spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension\" --conf \"spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog\""
  dist_classpath_filter: hadoop.*\.jar
```

**Notebook**

```scala
val data = spark.range(0, 5)
data.write.format("delta").save("/data/delta-table")
```

```sql
SELECT * from delta.`/data/delta-table`
```

**Logs**

```
Uncaught exception: loader constraint violation: when resolving method 'java.lang.Object org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(org.antlr.v4.runtime.ParserRuleContext, scala.Function0)' the class loader polynote.kernel.util.LimitedSharingClassLoader @60d1310 of the current class, io/delta/sql/parser/DeltaSqlAstBuilder, and the class loader 'app' for the method's defining class, org/apache/spark/sql/catalyst/parser/ParserUtils$, have different Class objects for the type org/antlr/v4/runtime/ParserRuleContext used in the signature (io.delta.sql.parser.DeltaSqlAstBuilder is in unnamed module of loader polynote.kernel.util.LimitedSharingClassLoader @60d1310, parent loader org.apache.spark.util.MutableURLClassLoader @4f2c9ba6; org.apache.spark.sql.catalyst.parser.ParserUtils$ is in unnamed module of loader 'app') (java.lang.LinkageError)
```

**Screenshots**
If applicable, please attach screenshots to help explain your problem.

**Additional context**
